version: '3.8'

services:
  svc:
    image: recsys/svc:latest
    ports:
      - "8000:8000"
    environment:
      ELASTIC_HOST: "elasticsearch"
      ELASTIC_PORT: 9200
    volumes:
      # for local dev refreshing
      - type: "bind"
        source: ./python/src/svc
        target: /src/svc
    depends_on:
      - "elasticsearch"
    entrypoint: sh -c 'uvicorn svc.main:app --reload --host 0.0.0.0 --port 8000'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    hostname: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  twins:
    image: recsys/twins:latest
    environment:
      ELASTIC_HOST: "elasticsearch"
      ELASTIC_PORT: 9200
    depends_on:
      - "elasticsearch"
      - "svc"
    volumes:
      - type: "bind"
        source: ./data
        target: /data
      - type: "bind"
        source: ./python/src
        target: /src
    entrypoint: python -c 'import twins; twins.v1.train_predict()'
